### ISSUE TITLE
ModuleNotFoundError: No module named 'author'

### ISSUE THREAD

**Issue by prashasy** [ButterCMS/flask-cms-blog-example#3]
I followed the instructions as per the readme. When i run app.py as given in the sample project itself, it gives an error "No module name 'author' ".
The complete traceback is as following :

Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from buttercms.blog_blueprint import blog
  File "/Users/prashasy/Documents/projects/flask-cms-blog-example/buttercms/blog_blueprint.py", line 1, in <module>
    from butter_cms import ButterCMS
  File "/Users/prashasy/Documents/projects/virtual-env/lib/python3.6/site-packages/butter_cms/__init__.py", line 1, in <module>
    from author import Author
ModuleNotFoundError: No module named 'author'

**Comment by jakelumetta** [comment]
Hi - can you try upgrading to 1.1 of our Python package?

https://github.com/ButterCMS/flask-cms-blog-example/commit/ebd39b67e8e59906324fb360b4f83d8ae03c9f74

**Comment by prashasy** [comment]
Yeah that worked. I changed the requirements.txt file as well
Thanks a lot!
